import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';

extension BuildContextExtensions on BuildContext {
  AppLocalizations get translations {
    AppLocalizations? temp = AppLocalizations.of(this);

    if (temp == null) {
      throw ("""
        AppLocalizations not found. Probably it wasnt generated by flutter pub get.
        To enable to automatically generate by flutter pub get make sure that the generate flag is enabled in pubspec.yaml under flutter: section.
        You can try to generate translations alternatively by running the flutter gen-l10n command
      """);
    }
    return temp;
  }
}
