name: timer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  assets_audio_player: ^3.0.3+3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  intl: any
  sleek_circular_slider: ^2.0.0
  url_launcher: ^6.0.9

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#160c25"
  android: true
  ios: true
  image: "assets/logo.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/png/
    - assets/png/timer_lines/
    - assets/png/replay_background/
    - assets/png/mask_group/
    - assets/png/logo/
    - assets/png/aboutus/
    - assets/sounds/
    - assets/svg/


scripts:
  test:
    coverage:
      $description: "Generate the code test coverage report from scratch and open a webpage where you can check in details."
      $script: "flutter test test/ . --coverage && genhtml coverage/lcov.info -o coverage/html && open coverage/html/index.html"
